### ISSUE TITLE
Change LICENCE

### ISSUE THREAD

**Issue by ganesh-k13** [ganesh-k13/titanium-silver#22]
Update from MIT to Creative Commons

**Comment by Rahul-RB** [comment]
_As a formally accepted contributor of the titanium-silver, I hereby acknowledge the receipt of the aforementioned message and would like to extend my warmest regards._

Note: 
- `titanium-silver` refers to the name of the current repository.
- `contributor` in the context refers to a person or thing that contributes something to something in `particular`. Here the `particular` refers to `titanium-silver`.
