### ISSUE TITLE
Client CLI

### ISSUE THREAD

**Issue by ganesh-k13** [ganesh-k13/titanium-silver#6]
Provide a CLI of the form:

- [x] Upload file via `<prog> --upload file.ext --question 'question_hash'`. (`question_hash'` uniquely identifies a problem statement and maps to folder containing Problem input and output).
For example:
1. let's say linear search problem has hash 'aswe3432sa'. 
2. Your server will have a folder say /opt/aswe3432sa which has in.txt and out.txt.
3. You must upload the file to that folder (or anywhere of choice) and use that context to give in.txt and out.txt to docker.
4. NOTE: This is just a design choice. Please proceed however you find efficient.

- [x] Flask or Django server to receive the file and put it at the dockers mounted folder.

- [x] Send back results such as _SUCCESS!_, _Compilation Failed: msg: ..._, _Testcase 'n' failed_, etc

**Comment by Rahul-RB** [comment]
Shouldn't the client program calculate `code_hash` ?

**Comment by ganesh-k13** [comment]
`code_hash` is intended to uniquely identify a question. Like problem 1 will have `w234a`, etc. I'll rephrase it.

**Comment by ganesh-k13** [comment]
Please pull the latest master before sending new PRs. Massive changes to the interface.

**Comment by Rahul-RB** [comment]
Okay, will do

**Comment by Rahul-RB** [comment]
Closed in [PR 14](https://github.com/ganesh-k13/titanium-silver/pull/14#issue-220126682)
